<script setup>
import Tweet from "./Tweet.vue";

const tweet_data = [
  {
    name: "Jahrein",
    username: "@jahreindota",
    badge: true,
    time: "Jan 6",
    pp_route: "src/assets/img/person2-pp.jpg",
    image_route: false,
    text: "Uzun zaman yanlışı o kadar çok tekrar etmişiz ki normalmişçesine kültürümüze işlemiş bazı şeyler. Motorla yaya yoluna girene bir daha hiçbir motorlu taşıt sürdürmezler özendiğimiz batıda. Özenmekle kalmayalım, benzeyelim. Ne dersiniz?",
    comment: "67",
    retweet: "138",
    like: "8.2K",
  },
  {
    name: "Tarih Otağ",
    username: "@tarihotag",
    badge: false,
    time: "Aug 15",
    pp_route: "src/assets/img/person4-pp.jpg",
    image_route: "src/assets/img/image.jpg",
    text: "Şayet bir gün çaresiz kalırsanız kurtarıcı beklemeyin, kurtarıcı siz olun. Gazi Mustafa Kemal Atatürk",
    comment: "2",
    retweet: "148",
    like: "1.6K",
  },
  {
    name: "Cem Yılmaz",
    username: "@CMYLMZ",
    badge: true,
    time: "Nov 1",
    pp_route: "src/assets/img/person5-pp.jpg",
    image_route: false,
    text: "Dün gösteri iki saat kala yağan yağmurdan iptal oldu.Olur insanlık hali ! ben Nazilliden geldim otopark paramı kim verecük yazmış. Ben vereceğim çünkü bütün parayı ben topluyorum otopark otobüs yolda yenilen poğaça çöp şiş bunları hep ben ödeyeceğim. Bunun doğrusu budur.",
    comment: "1.1K",
    retweet: "820",
    like: "32.2K",
  },
  {
    name: "Özgür Demirtaş",
    username: "@ProfDemirtas",
    badge: true,
    time: "March 13",
    pp_route: "src/assets/img/person1-pp.jpg",
    image_route: false,
    text: "Fazla tevazunun sonu vasat adamdan nasihat dinlemektir.",
    comment: "791",
    retweet: "9K",
    like: "98K",
  },
  {
    name: "Haluk Tatar",
    username: "@haluktatar",
    badge: true,
    time: "Aug 15",
    pp_route: "src/assets/img/person3-pp.jpg",
    image_route: false,
    text: "Sel-Deprem-Yangın... Doğal afete maruz kalan afetzedelere borç ya da faizsiz kredi vermek marifet değil! Zaten her şeyini kaybetmiş aileye borç değil, HİBE VERECEK DEVLET! Yıllarca maaşlardan, vergilerden kesiyorsunuz. Somali’ye 30 milyon dolar verebiliyorsak, bize de olmalı!",
    comment: "13",
    retweet: "147",
    like: "1.5K",
  },
  {
    name: "Jahrein",
    username: "@jahreindota",
    badge: true,
    time: "Jan 6",
    pp_route: "src/assets/img/person2-pp.jpg",
    image_route: false,
    text: "Uzun zaman yanlışı o kadar çok tekrar etmişiz ki normalmişçesine kültürümüze işlemiş bazı şeyler. Motorla yaya yoluna girene bir daha hiçbir motorlu taşıt sürdürmezler özendiğimiz batıda. Özenmekle kalmayalım, benzeyelim. Ne dersiniz?",
    comment: "67",
    retweet: "138",
    like: "8.2K",
  },
  {
    name: "Tarih Otağ",
    username: "@tarihotag",
    badge: false,
    time: "Aug 15",
    pp_route: "src/assets/img/person4-pp.jpg",
    image_route: "src/assets/img/image.jpg",
    text: "Şayet bir gün çaresiz kalırsanız kurtarıcı beklemeyin, kurtarıcı siz olun. Gazi Mustafa Kemal Atatürk",
    comment: "2",
    retweet: "148",
    like: "1.6K",
  },
  {
    name: "Cem Yılmaz",
    username: "@CMYLMZ",
    badge: true,
    time: "Nov 1",
    pp_route: "src/assets/img/person5-pp.jpg",
    image_route: false,
    text: "Dün gösteri iki saat kala yağan yağmurdan iptal oldu.Olur insanlık hali ! ben Nazilliden geldim otopark paramı kim verecük yazmış. Ben vereceğim çünkü bütün parayı ben topluyorum otopark otobüs yolda yenilen poğaça çöp şiş bunları hep ben ödeyeceğim. Bunun doğrusu budur.",
    comment: "1.1K",
    retweet: "820",
    like: "32.2K",
  },
  {
    name: "Özgür Demirtaş",
    username: "@ProfDemirtas",
    badge: true,
    time: "March 13",
    pp_route: "src/assets/img/person1-pp.jpg",
    image_route: false,
    text: "Fazla tevazunun sonu vasat adamdan nasihat dinlemektir.",
    comment: "791",
    retweet: "9K",
    like: "98K",
  },
  {
    name: "Haluk Tatar",
    username: "@haluktatar",
    badge: true,
    time: "Aug 15",
    pp_route: "src/assets/img/person3-pp.jpg",
    image_route: false,
    text: "Sel-Deprem-Yangın... Doğal afete maruz kalan afetzedelere borç ya da faizsiz kredi vermek marifet değil! Zaten her şeyini kaybetmiş aileye borç değil, HİBE VERECEK DEVLET! Yıllarca maaşlardan, vergilerden kesiyorsunuz. Somali’ye 30 milyon dolar verebiliyorsak, bize de olmalı!",
    comment: "13",
    retweet: "147",
    like: "1.5K",
  },
  {
    name: "Jahrein",
    username: "@jahreindota",
    badge: true,
    time: "Jan 6",
    pp_route: "src/assets/img/person2-pp.jpg",
    image_route: false,
    text: "Uzun zaman yanlışı o kadar çok tekrar etmişiz ki normalmişçesine kültürümüze işlemiş bazı şeyler. Motorla yaya yoluna girene bir daha hiçbir motorlu taşıt sürdürmezler özendiğimiz batıda. Özenmekle kalmayalım, benzeyelim. Ne dersiniz?",
    comment: "67",
    retweet: "138",
    like: "8.2K",
  },
  {
    name: "Tarih Otağ",
    username: "@tarihotag",
    badge: false,
    time: "Aug 15",
    pp_route: "src/assets/img/person4-pp.jpg",
    image_route: "src/assets/img/image.jpg",
    text: "Şayet bir gün çaresiz kalırsanız kurtarıcı beklemeyin, kurtarıcı siz olun. Gazi Mustafa Kemal Atatürk",
    comment: "2",
    retweet: "148",
    like: "1.6K",
  },
  {
    name: "Cem Yılmaz",
    username: "@CMYLMZ",
    badge: true,
    time: "Nov 1",
    pp_route: "src/assets/img/person5-pp.jpg",
    image_route: false,
    text: "Dün gösteri iki saat kala yağan yağmurdan iptal oldu.Olur insanlık hali ! ben Nazilliden geldim otopark paramı kim verecük yazmış. Ben vereceğim çünkü bütün parayı ben topluyorum otopark otobüs yolda yenilen poğaça çöp şiş bunları hep ben ödeyeceğim. Bunun doğrusu budur.",
    comment: "1.1K",
    retweet: "820",
    like: "32.2K",
  },
  {
    name: "Özgür Demirtaş",
    username: "@ProfDemirtas",
    badge: true,
    time: "March 13",
    pp_route: "src/assets/img/person1-pp.jpg",
    image_route: false,
    text: "Fazla tevazunun sonu vasat adamdan nasihat dinlemektir.",
    comment: "791",
    retweet: "9K",
    like: "98K",
  },
  {
    name: "Haluk Tatar",
    username: "@haluktatar",
    badge: true,
    time: "Aug 15",
    pp_route: "src/assets/img/person3-pp.jpg",
    image_route: false,
    text: "Sel-Deprem-Yangın... Doğal afete maruz kalan afetzedelere borç ya da faizsiz kredi vermek marifet değil! Zaten her şeyini kaybetmiş aileye borç değil, HİBE VERECEK DEVLET! Yıllarca maaşlardan, vergilerden kesiyorsunuz. Somali’ye 30 milyon dolar verebiliyorsak, bize de olmalı!",
    comment: "13",
    retweet: "147",
    like: "1.5K",
  },
  {
    name: "Jahrein",
    username: "@jahreindota",
    badge: true,
    time: "Jan 6",
    pp_route: "src/assets/img/person2-pp.jpg",
    image_route: false,
    text: "Uzun zaman yanlışı o kadar çok tekrar etmişiz ki normalmişçesine kültürümüze işlemiş bazı şeyler. Motorla yaya yoluna girene bir daha hiçbir motorlu taşıt sürdürmezler özendiğimiz batıda. Özenmekle kalmayalım, benzeyelim. Ne dersiniz?",
    comment: "67",
    retweet: "138",
    like: "8.2K",
  },
  {
    name: "Tarih Otağ",
    username: "@tarihotag",
    badge: false,
    time: "Aug 15",
    pp_route: "src/assets/img/person4-pp.jpg",
    image_route: "src/assets/img/image.jpg",
    text: "Şayet bir gün çaresiz kalırsanız kurtarıcı beklemeyin, kurtarıcı siz olun. Gazi Mustafa Kemal Atatürk",
    comment: "2",
    retweet: "148",
    like: "1.6K",
  },
  {
    name: "Cem Yılmaz",
    username: "@CMYLMZ",
    badge: true,
    time: "Nov 1",
    pp_route: "src/assets/img/person5-pp.jpg",
    image_route: false,
    text: "Dün gösteri iki saat kala yağan yağmurdan iptal oldu.Olur insanlık hali ! ben Nazilliden geldim otopark paramı kim verecük yazmış. Ben vereceğim çünkü bütün parayı ben topluyorum otopark otobüs yolda yenilen poğaça çöp şiş bunları hep ben ödeyeceğim. Bunun doğrusu budur.",
    comment: "1.1K",
    retweet: "820",
    like: "32.2K",
  },
  {
    name: "Özgür Demirtaş",
    username: "@ProfDemirtas",
    badge: true,
    time: "March 13",
    pp_route: "src/assets/img/person1-pp.jpg",
    image_route: false,
    text: "Fazla tevazunun sonu vasat adamdan nasihat dinlemektir.",
    comment: "791",
    retweet: "9K",
    like: "98K",
  },
  {
    name: "Haluk Tatar",
    username: "@haluktatar",
    badge: true,
    time: "Aug 15",
    pp_route: "src/assets/img/person3-pp.jpg",
    image_route: false,
    text: "Sel-Deprem-Yangın... Doğal afete maruz kalan afetzedelere borç ya da faizsiz kredi vermek marifet değil! Zaten her şeyini kaybetmiş aileye borç değil, HİBE VERECEK DEVLET! Yıllarca maaşlardan, vergilerden kesiyorsunuz. Somali’ye 30 milyon dolar verebiliyorsak, bize de olmalı!",
    comment: "13",
    retweet: "147",
    like: "1.5K",
  },
];
</script>

<template>
  <div class="tweets" v-for="(tweet, index) in tweet_data" :key="index">
    <Tweet :tweet="tweet" />
  </div>
</template>
